# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.CharField(max_length=30)),
                ('run_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_title', models.CharField(max_length=30)),
                ('shift_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.Shift'),
        ),
    ]
