# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_auto_20171119_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs_related', to='shift.Shift'),
        ),
    ]
