# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0008_auto_20171119_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
