# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0011_auto_20171123_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shiftGroup',
        ),
        migrations.AddField(
            model_name='shift',
            name='shiftGroup',
            field=models.ManyToManyField(blank=True, null=True, related_name='shifts_related', to='shift.ShiftGroup'),
        ),
    ]
